GET https://www.flickr.com/services/rest/?method=flickr.photos.search&api_key=af93a4865f55a4c5016a7ee52d598990&tags=cat&format=json&nojsoncallback=1
###
GET https://farm66.staticflickr.com/65535/50332481578_dc7392992c.jpg